version: "1"

services: 
    surfshark:
        image: jrparks/docker-proton
        container_name: proton
        environment: 
            - PROTON_USER=YOUR_PROTON_USER
            - PROTON_PASSWORD=YOUR_PROTON_PASSWORD
            - PROTON_CONFIG=YOUR CONFIG_FILE_NAME
            - LAN_NETWORK=192.168.0.0/24      #Optional - Used to access attached containers web ui
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        ports:
            - 9091:9091 #We open here the port for transmission, as this container will be the access point for the others
        restart: unless-stopped
        dns:
            - 1.1.1.1
    service_test:
        image: byrnedo/alpine-curl
        container_name: alpine
        command: -L 'https://ipinfo.io'
        depends_on: 
            - proton
        network_mode: service:proton
        restart: always
    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Rome
        #ports:
            #- 9091:9091 needed to access transmission's GUI
        network_mode: service:proton
        restart: unless-stopped
